version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/app/uploads:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=/api
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - DATABASE_URL=postgresql://webapp_user:webapp_pass@postgres:5432/webapp_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - UPLOAD_DIR=/app/uploads
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=webapp_db
      - POSTGRES_USER=webapp_user
      - POSTGRES_PASSWORD=webapp_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  postgres_data: